[package]
name = "grc-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
console = "*"
itertools = "*"
lazy_static = "*"
debug_print = "*"
