[package]
name = "grc-rs"
version = "0.3.2"
edition = "2021"
license = "MIT"
description = "Generic Colouriser ported to Rust"

[dependencies]
console = "0.15"
lazy_static = "1.4"
debug_print = "1.0"
argparse = "0.2"
which = "6.0"
fancy-regex = "0.13"
shellexpand = "3.1"